spring.application.name=ServerApp
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/673604?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
spoonacular.api.key=f05a2e706fb74601a0a864101668130c

api.url.drink=https://www.thecocktaildb.com/api/json/v1/1/search.php?f=
api.url.food=https://api.spoonacular.com/recipes/complexSearch